/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cerrato_aaron_idclase;


/**
 *
 * @author user
 */
public class CambiarPalabras extends javax.swing.JFrame {
String palabrasViejas = "";
    /**
     * Creates new form CambiarPalabras
     */
    public CambiarPalabras() {
        for (int i = 0;i<10;i++)
        {
        palabrasViejas +=Cerrato_Aaron_IDClase.palabras[i]+"  ";
        }
        initComponents();
        this.setResizable(false);
        this.setTitle("Juego");
        this.setLocationRelativeTo(null);
        Viejas.setText(palabrasViejas);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PalabraNueva = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Viejas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PalabraNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalabraNuevaActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        Viejas.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(PalabraNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Viejas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Viejas)
                .addGap(95, 95, 95)
                .addComponent(PalabraNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PalabraNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalabraNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PalabraNuevaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PalabraNueva;
    private javax.swing.JLabel Viejas;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
