/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cerrato_aaron_idclase;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Juego extends javax.swing.JFrame {
    int longitudArray = 10;
    Random r = new Random();
    int numeroR= (r.nextInt(9)+1);
    String palabra = Cerrato_Aaron_IDClase.palabras[numeroR];
    int intentos = 5;
    String dashes = "";
    String nuevoDash = "";
    
    /**
     * Creates new form Juego
     */
    public Juego() {
        for (int i = 0;i<palabra.length();i++)
            {
            dashes += "_ ";
            }
        nuevoDash = dashes;
        initComponents();
        this.setResizable(false);
        this.setTitle("Juego");
        this.setLocationRelativeTo(null);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITULO = new javax.swing.JLabel();
        Intentos = new javax.swing.JLabel();
        Respuesta = new javax.swing.JTextField();
        TEXTOINGRESECARACTER = new javax.swing.JLabel();
        laPalabraEnDashes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 480));

        TITULO.setText("AHORCADO");

        Intentos.setText("Intentos:"+intentos);

        TEXTOINGRESECARACTER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TEXTOINGRESECARACTER.setText("Ingrese un caracter");

        laPalabraEnDashes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laPalabraEnDashes.setText("jLabel2");
        if (nuevoDash.equals(""))
        {
            laPalabraEnDashes.setText(dashes);

        }
        else
        {
            laPalabraEnDashes.setText(nuevoDash);
        }

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TEXTOINGRESECARACTER)
                        .addGap(302, 302, 302))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(313, 313, 313))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TITULO)
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(laPalabraEnDashes, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)))
                        .addComponent(Intentos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TITULO)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Intentos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laPalabraEnDashes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TEXTOINGRESECARACTER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
String textoResp = Respuesta.getText().trim();

if (textoResp.isEmpty())
{
    JOptionPane.showMessageDialog(this,"No puedes dejar el mensaje vacio!");
    Respuesta.setText("");
    return;
}
if (textoResp.length()>1)
{
JOptionPane.showMessageDialog(this, "No puedes poner mas de una letra");
Respuesta.setText("");
return;
}



if (!(textoResp.equals(" ")) && intentos != 0)
{
    boolean encontrado = false;

    String temporal = "";
        for (int j = 0;j<palabra.length();j++)
        {
            if (textoResp.length()==1)//Revisar si solo es una letra
        {
            
            char letra = Respuesta.getText().charAt(0);
            if (Character.toLowerCase(letra) == Character.toLowerCase(palabra.charAt(j)))
                {
                    temporal += palabra.charAt(j) + " ";
                    encontrado = true;
                }
            else if (nuevoDash.charAt(j*2) != '_')
            {
            temporal += nuevoDash.charAt((j*2))+" ";
            }
            else 
            {
            temporal += "_ ";
            }
            
        }
        
        }
        
        if (!encontrado)
        {
        intentos --;
        }
        nuevoDash = temporal;
        laPalabraEnDashes.setText(nuevoDash);
        Intentos.setText("Intentos:"+intentos);
        if (nuevoDash.replaceAll(" ", "").equals(palabra))
        {
        JOptionPane.showMessageDialog(this, "Encontraste la palabra con "+intentos+" intentos restantes!");
        Cerrato_Aaron_IDClase menu = new Cerrato_Aaron_IDClase();
        menu.setVisible(true);
        dispose();
        }
        
        
        Respuesta.setText("");
        
        if (intentos == 0)
{
    JOptionPane.showMessageDialog(this, "No se adivino la palabra:(\n"+"La palabra era: "+palabra);
    Cerrato_Aaron_IDClase menu = new Cerrato_Aaron_IDClase();
    menu.setVisible(true);
    dispose();
}
}

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Intentos;
    private javax.swing.JTextField Respuesta;
    private javax.swing.JLabel TEXTOINGRESECARACTER;
    private javax.swing.JLabel TITULO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel laPalabraEnDashes;
    // End of variables declaration//GEN-END:variables
}
